#+TITLE: Compline According to the Monastic Use of the Roman Rite
#+SUBTITLE: English Text Only
#+AUTHOR: Alex Harter
#+DATE: <2024-01-04 Thu>
#+SOURCE: Monastic Diurnal, 1963, 7th Edition 2011, St. Michael's Abbey Press, p.256-269
https://docs.google.com/document/d/1h8Mn4IVSAtYN2b6lJnkE56noWwkROITOdzBTIZvyU-o/edit
* EXAMEN
V. Pray, father, a blessing.
Blessing: May almighty God grant us a peaceful night * and a perfect end.
R. Amen.
Lector: (1 Peter 5:8-9)
Brethren: Be sober and watch, † because your adversary the devil, as a roaring lion, goeth about seeking whom he may devour, * whom resist ye, strong in faith.
But Thou, O Lord, * have mercy on us.
R. Thanks be to God.

V. Our help is ✠ in the name of the Lord.

R. Who made heaven and earth.
(Examination of conscience.)
I confess to almighty God, to blessed Mary ever Virgin, to blessed Michael the Archangel, to blessed John the Baptist, to the holy Apostles Peter and Paul, to our holy Father Benedict, and to all the Saints, that I have sinned exceedingly in thought, word and deed: (strike breast x3:) through my fault, through my fault, through my most grievous fault. Therefore I pray Blessed Mary ever Virgin, blessed Michael the Archangel, blessed John the Baptist, the holy Apostles Peter and Paul, our holy Father Benedict, and all the Saints, to pray to the Lord our God for me.
May almighty God have mercy on us, forgive us our sins, and bring us to life everlasting.
R. Amen.
May the almighty ✠ and merciful Lord grant us pardon, absolution, and remission of our sins.

R. Amen.

* INTRODUCTION
V. Convert us, O God our Savior.
R. And turn away Thine anger from us.
V. O God, come to my assistance.
R. O Lord, make haste to help me.
Glory be to the Father, and to the Son, and to the Holy Spirit.
As it was in the beginning, is now, and ever shall be, world without end. Amen.
Alleluia.
After Septuagesima, instead of Alleluia:
Praise be to Thee, O Lord, King of eternal glory.

* PSALTER
** PSALM 4
1 When I cried for help, the God of my justice heard me; * when I was straightened Thou didst set me at large.
2 Have mercy on me, * and hear my prayer.
3 Ye sons of men, how long will you be hard of heart? * Why love vanities and have recourse to lying?
4 Know ye, that the Lord hath dealt wondrously with His holy one: * The Lord will hear me when I cry unto Him.
5 When roused to anger, sin not: † what you scheme in your hearts, * deplore upon your beds.
6 Offer a righteous sacrifice † and put your trust in the Lord. * Many there are that say: Who will show us good things?
7 Let the light of Thy countenance shine upon us, O Lord! * Thou hast given gladness to my heart,
8 Greater than the joy in rich harvests * of corn and wine and oil.
9 In peace, then, * shall I sleep and rest;
10 For Thou, O Lord! * makest me rest secure.
11 Glory be to the Father, and to the Son, * and to the Holy Ghost.
12 As it was in the beginning, is now, and ever shall be, * world without end. Amen.
** Psalm 90
13 He that dwelleth in the shelter of the Most High, * and abideth in the shadow of the Almighty,
14 Shall say to the Lord: Thou art my protector and my refuge! * My God, in Whom I trust.
15 For He will rescue thee from the snare of the fowler, * and from the sharp word.
16 With His pinions will He shelter thee; * and under His wings thou shalt be secure;
17 Like a shield His truth shall guard thee; * thou shalt not fear the terrors of night,
18 Nor the arrow that flies by day, † nor the plague that prowleth in the dark, * nor the noonday attack of the demon.
19 A thousand shall fall at thy side † and ten thousand at thy right hand, * yet no evil shall come nigh to thee.
20 But with thine eyes thou shalt see * and behold the punishment of the wicked.
21 Because thou hast made the Lord thy hope, * and the Most High thy refuge,
22 No evil shall befall thee * nor any plague come near thy dwelling.

23 He hath given His angels charge over thee, * to keep thee in all thy ways;
24 They shall bear thee up in their hands, * lest thou dash thy foot against a stone.
25 Thou shalt tread upon the asp and the adder, * the lion and the dragon shalt thou trample under foot.
26 Because he hath put his trust in Me, I will deliver him; * I will protect him because he hath known My Name.
27 He will call upon Me, and I will hear him; † I will be with him in need, * I will rescue him and bring him honor.
28 With length of days I will satisfy him, * and show him My salvation.
29 Glory be to the Father, and to the Son, * and to the Holy Ghost.
30 As it was in the beginning, is now, and ever shall be, * world without end. Amen.

** PSALM 133
31 Come now, bless the Lord, * all ye servants of the Lord.
32 Who stand in the house of the Lord, * in the courts of the house of our God;
33 At night lift up your hands to the sanctuary, * and bless the Lord.
34 May the Lord bless thee from Sion, * He Who made heaven and earth!
35 Glory be to the Father, and to the Son, * and to the Holy Ghost.
36 As it was in the beginning, is now, and ever shall be, * world without end. Amen.
* HYMN
To Thee, before the close of day, *
Creator of the world, we pray
That with Thy wonted favor, Thou
Wouldst be our Guard and Keeper now.

From evil dreams defend our eyes.
From nightly fears and fantasies;
Tread under foot our ghostly foe
That no pollution we may know.

O Father, that we ask be done,
Through Jesus Christ, thine only Son;
Who, with the Holy Ghost and Thee,
Shall live and reign eternally.
Amen.
# :TODO: add alternate doxologies
* CHAPTER & VERSICLE
/Jeremaiah 14:9/
Thou, O Lord, art among us, † and Thy holy Name is called upon by us; * forsake us not, O Lord our God.
R. Thanks be to God.

V. Keep us, O Lord, as the apple of Thine eye. (Alleluia.)
R. Protect us under the shadow of Thy wings. (Alleluia.)
* ORATION
V. Lord, have mercy on us.
R. Christ, have mercy on us.  Lord, have mercy on us.
   Our Father, … (silently, until:)

V.  And lead us not into temptation.
R.  But deliver us from evil.

V.  O Lord, hear my prayer.
R.  And let me cry come unto Thee.

Let us pray.
Visit, we beseech thee, O Lord, this dwelling, and drive far from it the snares of the enemy; † let thy holy angels dwell herein to preserve us in peace, * and let Thy blessing be always upon us.
Through our Lord Jesus Christ, Thy Son, † Who liveth and reigneth with Thee in the unity of the Holy Ghost, God, * world without end.

R. Amen.
* CONCLUSION
V.  O Lord, hear my prayer.
R. And let my cry come unto Thee.
V.  Let us bless the Lord.
R.  Thanks be to God.
(Slowly, in a low tone:)
May the almighty and merciful Lord, ✠ the Father, the Son and the Holy Ghost, bless us and keep us.
R. Amen.
* FINAL ANTIPHON OF THE BLESSED VIRGIN MARY
** From I Vespers of the First Sunday in Advent until February 1 inclusive:
Gracious Mother of our Redeemer, for ever abiding
Heaven’s gateway, and star of ocean, O succor the people,
Who, though falling, strive to rise again.
Thou Maiden who nearest thy holy Creator, to the wonder of all nature;
Ever Virgin, after, as before thou receivedst that Ave
From the mouth of Gabriel; have compassion on us sinners.
*** Through December 23:
V. The Angel of the Lord declared unto Mary.
R. And she conceived of the Holy Ghost.

Let us pray.
Pour forth, we beseech Thee, O Lord, Thy grace into our hearts; † that we, to whom the incarnation of Christ, Thy Son, was made known by the message of an Angel, * may by His Passion and Cross be brought to the glory of His Resurrection.
Through the same Christ Our Lord.

R. Amen.
*** From December 24:
V. After childbirth thou didst remain an inviolate Virgin.
R. Mother of God, pray for us.

Let us pray.
O God, Who by the fruitful virginity of Blessed Mary hast given to mankind the rewards of eternal salvation, † grant, we beseech Thee, that we may experience her intercession for us * through whom we received the Author of life,
Our Lord Jesus Christ, Thy Son.

R. Amen.

** From February 2, even if the Feast of the Purification has been transferred, through Wednesday of Holy Week:
Queen of the heavens, we hail thee,
Hail thee, Lady of all the Angels;
Thou the dawn, the door of morning
Whence the world’s true Light is risen:

Joy to thee O Virgin glorious,
Beautiful beyond all other;
Hail, and farewell, O most gracious,
Intercede for us always to Jesus.

V. Grant that I may praise thee, O holy Virgin.
R. Give me strength against thine enemies.

Let us pray.
Grant, O merciful God, help to our weakness, † that we who commemorate the holy Mother of God, * may by the help of her intercession rise from our sins.

Through the same Christ our Lord.

R. Amen.
** From Easter Sunday through None of Trinity Eve, inclusive:
Queen of heaven, rejoice, alleluia!
For He whom thou wast chosen to bear, alleluia!
Has risen as He said, alleluia!
Pray for us to God, alleluia!
V. Rejoice and be glad, O Virgin Mary, alleluia!
R. For the Lord is truly risen, alleluia!

Let us pray.
O God, Who didst deign to give joy to the world through the resurrection of Thy Son our Lord Jesus Christ, † grant, we beseech Thee, that through His Mother, the Virgin Mary, * we may obtain the joys of everlasting life.
Through the same Christ our Lord.

R. Amen.
** From I Vespers on Trinity Eve until I Vespers of the first Sunday of Advent:
Hail! Holy queen Queen, Mother of mercy, our life, our sweetness and our hope. To thee do we cry, poor banished children of Eve. To thee do we send up our sighs, mourning and weeping in this valley of tears. Turn then, most gracious advocate, thine eyes of mercy towards us. And after this our exile, show unto us the blessed fruit of thy womb, Jesus. O clement, O loving, O sweet Virgin Mary.
V. Pray for us, O holy Mother of God.
R. That we may be made worthy of the promises of Christ.

Let us pray.
Almighty and everlasting God, Who by the cooperation of the Holy Ghost didst make ready the body and soul of the glorious Virgin and Mother Mary to be a fit dwelling for Thy Son, † grant that we, who rejoice in her memory, * may be freed from present ills and from eternal death by her prayers.
Though the same Christ our Lord.

R. Amen.
* FINALLY
V. May the divine assistance ✠ remain with us always.
R. Amen.
